wpengine/headless-docs

guides/getting-started/README.md
Recommending minor text tweaks on "Getting Started" page for consistency/clarity/polish.
=> [HEADLESS-399] Copyedit "Getting Started" page

guides/getting-started/create-app.md
Recommending minor text tweaks on "Create Your First App" page for consistency/clarity/polish.
=> [HEADLESS-399] Copyedit create-app.md

guides/getting-started/README.md, guides/getting-started/deploy-app.md, guides/getting-started/workflow.md
Recommending minor text tweaks on "Deploy Your First App" page for consistency/clarity/polish.
=> [HEADLESS-399] Copyedit "Deploy Your First App" page

README.md
Add notes on how to install the CLI
=> Add notes on how to install the CLI tool

README.md, guides/README.md, guides/getting-started/deploy-app.md, guides/troubleshooting/README.md
Added a troubleshooting section with how to pull logs and making sure your package.json is setup correctly.
=> Added Troubleshooting

guides/getting-started/workflow.md
Updated with recently developed features:
- Standard logs retrieval
- Deleting environment
- Checking build status
=> Updated instructions for logs & delete

guides/getting-started/deploy-app.md
Should be merged when  release (production) of headless repository is done.
=> rename secrets to env_variables [GAIA-757]

README.md, guides/getting-started/deploy-app/README.md, reference/cli/wpe/alpha/apps/create/README.md
- Added `region` to apps
- Added `domains` to environments
=> Platform v0.0.8 Updates

README.md
=> Fix link to WP Engine User Portal

guides/getting-started/deploy-app/cli/README.md
This PR updates our alpha commands to the correct ones for the latest version of `wpe`
=> Remove alpha refs from deploy commands

README.md
We now support more than one custom domain.
=> Remove note about custom domain support

node-engine/guides/getting-started.mdx
* Update getting-started.mdx
* Fixed typos
* Update getting-started.mdx
* Added hyperlink to Docker docs
=> Node versions update (#68)

atlas/local-app-development/wordpress-site-config.mdx
=> Spell check - Monterey

atlas/local-app-development/overview.mdx
One of the internal links on my last PR was not relative and resulted in a 404, this updates that link target
=> update link on local dev overview

atlas-search/introduction.mdx
Pt. 2 - Format Images & h1 -> h2 as directed
=> docs: ✏️ Update image paths & title h1 -> h2 in md

atlas-search/introduction.mdx
Reverts wpengine/headless-docs#131
=> Revert "Thed00de searchgettingstarted 1"

atlas/additional-guides/troubleshooting-builds.mdx
Added description of 2 most common issues that user experience while creating their Blueprint apps. Happy to make any changes requested during the review!
=> Addressing common issues with Blueprints

atlas/customization/builds.mdx
npm should be Yarn in this section
=> [NEB-1154] Fix npm/yarn mistake in build docs

atlas/additional-guides/domain-mapping.mdx
Description of redirect rules mechanism in User Portal along with screenshots and CLI-related constraints.
=> Update domain mapping docs with redirects

atlas/reference/cli/wpe/apps/create.mdx, glossary/index.mdx, package-lock.json
https://wpengine.atlassian.net/browse/DEVREL-752
Broken link on this ticket fixed
=> Fix to 404 Page from create cli page

atlas/additional-guides/domain-mapping.mdx
Update Domain Mapping Guide to include info about setting a custom domain for the WordPress install.
=> Update Domain Mapping Guide for custom WP domain

atlas/customization/builds.mdx
Hi team! Webhooks are now open for everyone - can we push this small update to docs as well?
=> Remove the need to sign-up for webhooks

atlas/config.json, atlas/reference/non-cli/zip-upload.mdx
Also modified a line of zip upload description I forgot to push with last PR
=> fix: 🐛 Modified menu path to move Non-CLI out of CLI Reference

atlas-search/using-atlas-search.mdx
fix broken links on atlas search pages
=> fix: NOJIRA atlas search image links

atlas-search/introduction.mdx, atlas-search/using-atlas-search.mdx
update wordpress to correct caps
=> J everhart383 patch 1

atlas/getting-started/blueprint-repository.mdx
Reverts wpengine/headless-docs#272
=> Revert "Update blueprint-repository.mdx"

atlas-search/public-api/find.md
Update Search API documentation to reflect a graphql example
=> ORN-1888 Atlas Search / Add find query example

atlas/additional-guides/troubleshooting-builds.mdx
Sadly, the mechanism of handling repo name changes is broken at the moment. Adding a note so that it's reflected in docs. 
Please check the option that describes the scope of the change you are requesting.
- Small
NOTE: Please keep these timelines in mind when preparing docs changes.
- Small changes will get processed ASAP.
- Medium changes will depend on the workload and may get ticketed for next sprint.
- Large changes will always need a ticket in our next sprint.
=> Update description of what happens in case of changed repo name

atlas-search/public-api/index.md, atlas/additional-guides/troubleshooting-builds.mdx
A feature with the Git providers is broken adding note
Please check the option that describes the scope of the change you are requesting.
- [x ] Small (fixing typos, changing lines of an existing doc, etc.)
NOTE: Please keep these timelines in mind when preparing docs changes.
- Small changes will get processed ASAP.
- Medium changes will depend on the workload and may get ticketed for next sprint.
- Large changes will always need a ticket in our next sprint.
=> update git provider info

atlas-search/using-atlas-search.mdx
Link to ticket: https://wpengine.atlassian.net/browse/ORN-2053
- 
- 
- 
- 
- 
-
=> [ORN-2053] - Update docs that AS has stopped support for ACM since v0.2.14
